apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jharting-edit
  namespace: rhn-engineering--2-tenant
subjects:
- kind: User
  name: rhn-engineering--2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
